import {
    Box,
    Layers,
    Zap,
    LayoutGrid,
    Sparkles,
    Book,
    FileText,
    Shield,
    HelpCircle,
    Globe,
    User,
    Settings,
    ArrowRightLeft,
    Home,
    Twitter,
    Github,
    Send,
    Mail,
    ShoppingBag,
    Rocket,
    BarChart,
    Wallet,
    History,
    LifeBuoy,
    Code,
    Calendar,
    Edit,
    PlusCircle,
    LayoutTemplate
} from "lucide-react"

export const navigation = {
    main: [
        { title: "Start", href: "/", icon: Home, description: "medialane.io" },
        { title: "Marketplace", href: "/marketplace", icon: ShoppingBag, description: "Trade onchain assets" },
        { title: "Launchpad", href: "/launchpad", icon: Rocket, description: "Creator Launchpad" },
        { title: "Portfolio", href: "/portfolio", icon: User, description: "Manage your onchain account" },
    ],
    marketplace: [
        { title: "Marketplace", href: "/marketplace", icon: ShoppingBag, description: "Trade onchain assets" },
        { title: "Explore NFTs", href: "/assets", icon: Box, description: "Browse all IP assets" },
        { title: "Collections", href: "/collections", icon: Layers, description: "View all collections" },
        { title: "Community", href: "/activities", icon: BarChart, description: "Protocol activity" },
    ],
    launchpad: [
        { title: "Creator Launchpad", href: "/launchpad", icon: Rocket, description: "Creator tools dashboard" },
        { title: "Creator Studio", href: "/create", icon: Rocket, description: "Creator studio" },
        { title: "Standard Collection", href: "/launchpad/single-editions/collection", icon: PlusCircle, description: "Start from scratch" },
        { title: "Mint Asset", href: "/launchpad/single-editions", icon: Box, description: "Mint single asset" },
        { title: "Create with IP Templates", href: "/create/templates", icon: LayoutTemplate, description: "Use legal templates" },
    ],
    portfolio: [
        { title: "Onchain Dashboard", href: "/portfolio", icon: Box, description: "Your portfolio dashboard" },
        { title: "My Assets", href: "/portfolio/assets", icon: Box, description: "Your owned IP" },
        { title: "My Collections", href: "/portfolio/collections", icon: Layers, description: "Collections you created" },
        { title: "My Activities", href: "/portfolio/activities", icon: History, description: "Your activities" },
        { title: "My Listings", href: "/portfolio/listings", icon: Box, description: "Your active sale listings" },
        { title: "My Offers", href: "/portfolio/offers", icon: Box, description: "Your active buy offers" },
        { title: "Offers Received", href: "/portfolio/offers-received", icon: Box, description: "Offers received on your assets" },
    ],
    discover: [
        { title: "IP Assets", href: "/assets", icon: Box, description: "Explore registered IP assets" },
        { title: "Collections", href: "/collections", icon: Layers, description: "Browse curated IP collections" },
        { title: "Activities", href: "/activities", icon: Zap, description: "Protocol activities" },
        { title: "Marketplace", href: "/marketplace", icon: ShoppingBag, description: "Trade onchain assets" },
    ],
    create: [
        { title: "Creator Studio", href: "/create", icon: Rocket, description: "Creator tools dashboard" },
        { title: "IP Collection", href: "/launchpad/single-editions/collection", icon: PlusCircle, description: "Start from scratch" },
        { title: "IP Asset", href: "/launchpad/single-editions", icon: Box, description: "Mint single asset" },
        { title: "Create NFT", href: "/create/templates/nft", icon: Box, description: "Create NFT" },
        { title: "IP Templates", href: "/create/templates", icon: LayoutTemplate, description: "Use legal templates" },
    ],
    resources: [
        { title: "Documentation", href: "https://docs.medialane.io", icon: FileText, description: "Technical guides & API refs" },
        { title: "User Guide", href: "https://docs.medialane.io/user-guide", icon: Code, description: "User guide" },
        { title: "Permissionless Setup", href: "https://docs.medialane.io/permissionless-setup", icon: Code, description: "Permissionless setup" },
        { title: "Community Guidelines", href: "https://docs.medialane.io/community-guidelines", icon: Shield, description: "Community rules and conduct code" },
        { title: "Compliance Guidelines", href: "https://docs.medialane.io/compliance-guidelines", icon: Code, description: "Compliance orientation" },
        { title: "Dapp Guidelines", href: "https://docs.medialane.io/dapp-guidelines", icon: Code, description: "Know our dapp guidelines" },
        { title: "Developers", href: "https://medialane.xyz", icon: Code, description: "SDKs and tools" },
        { title: "Privacy Policy", href: "https://docs.medialane.io/privacy-policy", icon: Code, description: "Privacy policy" },
        { title: "Terms of Use", href: "https://docs.medialane.io/terms-of-use", icon: Code, description: "Terms of use" },
    ],
    socials: [
        { title: "X (Twitter)", href: "https://x.com/medialane_io", icon: Twitter },
        { title: "GitHub", href: "https://github.com/medialane-io", icon: Github },
        { title: "Telegram", href: "https://t.me/integrityweb", icon: Send },
        { title: "Email", href: "mailto:dao@medialane.org", icon: Mail },
    ]
}
